### ISSUE TITLE
Could you help me with undertanding this

### ISSUE THREAD

**Issue by Sreedeep-rougeloop** [ChrisPritchard/ctf-writeups#1]
Consider the following bytecode:

LDC 0

LDC 3

SWAP

POP

INEG

Which value is now at the top of the stack?

**Comment by ChrisPritchard** [comment]
Er, its -3 isn't it? add 0, then add 3 which makes the stack 3|0, swap so its 0|3, pop so its 3, ineg makes it -3?

**Comment by rogueloop** [comment]
yes thanks ✌
